-- Migration 133: three-level category tree (L1 > L2 > L3)
--
-- Generated by scripts/gen-category-tree-seed.mjs from docs/tree.csv. Do not hand-edit;
-- change the CSV or the mapping tables in that script and regenerate.
--
-- Additive and idempotent. categories_l3 keeps its primary key and every row, so the six
-- tables that reference it (projects, rfqs, compliance_requests, compliance_requirements,
-- product_features, supplier_proposals) and category_attributes are untouched.

BEGIN;

-- 1. Parent levels ---------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.categories_l1 (
  id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name       text NOT NULL UNIQUE,
  sort_order integer NOT NULL DEFAULT 0,
  active     boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.categories_l2 (
  id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  l1_id      uuid NOT NULL REFERENCES public.categories_l1(id) ON DELETE RESTRICT,
  name       text NOT NULL,
  sort_order integer NOT NULL DEFAULT 0,
  active     boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (l1_id, name)
);

CREATE INDEX IF NOT EXISTS idx_categories_l2_l1_id ON public.categories_l2(l1_id);

-- 2. Hang the existing leaf table off L2 -----------------------------------
-- Nullable on purpose: a leaf with no parent is the "Uncategorised" bucket, which is
-- where unmatched legacy rows land rather than being deleted.

ALTER TABLE public.categories_l3
  ADD COLUMN IF NOT EXISTS l2_id uuid REFERENCES public.categories_l2(id) ON DELETE RESTRICT,
  ADD COLUMN IF NOT EXISTS sort_order integer NOT NULL DEFAULT 0;

CREATE INDEX IF NOT EXISTS idx_categories_l3_l2_id ON public.categories_l3(l2_id);

COMMENT ON COLUMN public.categories_l3.l2_id IS
  'Parent L2. NULL means uncategorised - the row is kept and usable but sits outside the tree.';

-- 3. RLS - mirror categories_l3 exactly ------------------------------------

ALTER TABLE public.categories_l1 ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories_l2 ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Enable all for categories_l1" ON public.categories_l1;
CREATE POLICY "Enable all for categories_l1" ON public.categories_l1
  FOR ALL USING (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Allow public read access to categories_l1" ON public.categories_l1;
CREATE POLICY "Allow public read access to categories_l1" ON public.categories_l1
  FOR SELECT USING (true);

DROP POLICY IF EXISTS "Enable all for categories_l2" ON public.categories_l2;
CREATE POLICY "Enable all for categories_l2" ON public.categories_l2
  FOR ALL USING (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Allow public read access to categories_l2" ON public.categories_l2;
CREATE POLICY "Allow public read access to categories_l2" ON public.categories_l2
  FOR SELECT USING (true);

-- 4. Seed L1 ----------------------------------------------------------------

INSERT INTO public.categories_l1 (name, sort_order) VALUES
  ('Large Appliances', 10),
  ('Small Appliances', 20),
  ('Climate', 30),
  ('Home & Décor', 40),
  ('Sports & Leisure', 50),
  ('Garden', 60),
  ('Audio', 70)
ON CONFLICT (name) DO NOTHING;

-- 5. Seed L2 ----------------------------------------------------------------

INSERT INTO public.categories_l2 (l1_id, name, sort_order)
SELECT l1.id, v.l2_name, v.sort_order
FROM (VALUES
  ('Large Appliances', 'Clothes Dryers', 10),
  ('Large Appliances', 'Dishwashers', 20),
  ('Large Appliances', 'Freezers', 30),
  ('Large Appliances', 'Hobs', 40),
  ('Large Appliances', 'Humidors', 50),
  ('Large Appliances', 'Microwave Ovens', 60),
  ('Large Appliances', 'Ovens', 70),
  ('Large Appliances', 'Range Hoods', 80),
  ('Large Appliances', 'Refrigerators', 90),
  ('Large Appliances', 'Wine Coolers', 100),
  ('Small Appliances', 'Air Fryers', 10),
  ('Small Appliances', 'Beer Brewing & Dispensing', 20),
  ('Small Appliances', 'Coffee Makers', 30),
  ('Small Appliances', 'Electric Grills', 40),
  ('Small Appliances', 'Food Dehydrators', 50),
  ('Small Appliances', 'Hot Dog Makers', 60),
  ('Small Appliances', 'Ice Cream Makers', 70),
  ('Small Appliances', 'Ice Makers', 80),
  ('Small Appliances', 'Kettles', 90),
  ('Small Appliances', 'Kitchen Machines', 100),
  ('Small Appliances', 'Meat Grinders', 110),
  ('Small Appliances', 'Milk Makers', 120),
  ('Small Appliances', 'Mini Ovens', 130),
  ('Small Appliances', 'Pasta Makers', 140),
  ('Small Appliances', 'Pizza Ovens', 150),
  ('Small Appliances', 'Popcorn Makers', 160),
  ('Small Appliances', 'Preserving Pots', 170),
  ('Small Appliances', 'Sous Vide', 180),
  ('Small Appliances', 'Toasters', 190),
  ('Small Appliances', 'Vacuum Cleaners', 200),
  ('Small Appliances', 'Water Filters', 210),
  ('Climate', 'Air Purifiers', 10),
  ('Climate', 'Cooling', 20),
  ('Climate', 'Dehumidifiers', 30),
  ('Climate', 'Indoor Heaters', 40),
  ('Climate', 'Outdoor Heaters', 50),
  ('Climate', 'Water Heaters', 60),
  ('Home & Décor', 'Bathroom', 10),
  ('Home & Décor', 'Dining & Tableware', 20),
  ('Home & Décor', 'Kitchen', 30),
  ('Home & Décor', 'Living & Home Accessories', 40),
  ('Home & Décor', 'Waste & Storage', 50),
  ('Sports & Leisure', 'Fitness Machines', 10),
  ('Sports & Leisure', 'Games & Entertainment', 20),
  ('Sports & Leisure', 'Kids Sports & Play', 30),
  ('Garden', 'Garden Furniture', 10),
  ('Garden', 'Garden Structures & Shade', 20),
  ('Garden', 'Garden Utilities', 30),
  ('Garden', 'Gardening & Equipment', 40),
  ('Garden', 'Grills', 50),
  ('Garden', 'Outdoor Cooking & Kitchens', 60),
  ('Audio', 'Hifi Systems & Components', 10),
  ('Audio', 'Home Theaters', 20)
) AS v(l1_name, l2_name, sort_order)
JOIN public.categories_l1 l1 ON l1.name = v.l1_name
ON CONFLICT (l1_id, name) DO NOTHING;

-- 6. Rename the hand-mapped legacy rows to their canonical CSV leaf ---------
-- Ids are preserved, so all attributes, projects and requirements ride along.

UPDATE public.categories_l3 SET name = 'Infrared Panels'
  WHERE id = 'd75a7122-a9d8-478c-b9d4-2a44188353b0' AND name = 'Designer Infrared Panels';  -- Designer Infrared Panels -> Infrared Panels
UPDATE public.categories_l3 SET name = 'Glass-Ceramic Hobs'
  WHERE id = 'f1df6682-f7ec-4884-8867-3c2534a15809' AND name = 'VTC Hobs';  -- VTC Hobs -> Glass-Ceramic Hobs
UPDATE public.categories_l3 SET name = 'Fountains'
  WHERE id = '9ffbaa75-ee7b-4b5d-acdf-c1d712196aa7' AND name = 'Solar Fountains';  -- Solar Fountains -> Fountains
UPDATE public.categories_l3 SET name = 'Automatic Coffee Machines'
  WHERE id = '8d9090c0-05eb-4798-a4e1-95392a04a72c' AND name = 'Coffee Machines';  -- Coffee Machines -> Automatic Coffee Machines
UPDATE public.categories_l3 SET name = 'Home Dehumidifiers'
  WHERE id = '2042b131-f838-46ba-980f-9e4efa5f6df2' AND name = 'Dehumidifiers';  -- Dehumidifiers -> Home Dehumidifiers
UPDATE public.categories_l3 SET name = 'Freestanding Wine Coolers'
  WHERE id = '03c60698-a048-425d-8a45-45e1d2570a2d' AND name = 'Wine Fridges';  -- Wine Fridges -> Freestanding Wine Coolers

-- 7. Seed / file L3 ---------------------------------------------------------
-- Match by name against the leaves that already exist: an existing row is filed under
-- its L2, a missing one is inserted. Never deletes.

CREATE TEMP TABLE _tree_l3 (l1_name text, l2_name text, l3_name text, sort_order integer) ON COMMIT DROP;

INSERT INTO _tree_l3 (l1_name, l2_name, l3_name, sort_order) VALUES
  ('Large Appliances', 'Clothes Dryers', 'Clothes Dryers', 10),
  ('Large Appliances', 'Dishwashers', 'Built-In Dishwashers', 10),
  ('Large Appliances', 'Dishwashers', 'Tabletop Dishwashers', 20),
  ('Large Appliances', 'Dishwashers', 'Freestanding Dishwashers', 30),
  ('Large Appliances', 'Freezers', 'Mini Freezers', 10),
  ('Large Appliances', 'Freezers', 'Freestanding Freezers', 20),
  ('Large Appliances', 'Freezers', 'Chest Freezers', 30),
  ('Large Appliances', 'Hobs', 'Induction Hobs', 10),
  ('Large Appliances', 'Hobs', 'Gas Hobs', 20),
  ('Large Appliances', 'Hobs', 'Hobs with Integrated Hoods', 30),
  ('Large Appliances', 'Hobs', 'Glass-Ceramic Hobs', 40),
  ('Large Appliances', 'Hobs', 'Tabletop Hobs', 50),
  ('Large Appliances', 'Hobs', 'Hybrid Hobs', 60),
  ('Large Appliances', 'Hobs', 'Electric Hobs', 70),
  ('Large Appliances', 'Hobs', 'Combination Hobs', 80),
  ('Large Appliances', 'Humidors', 'Humidors', 10),
  ('Large Appliances', 'Microwave Ovens', 'Built-In Microwave Ovens', 10),
  ('Large Appliances', 'Microwave Ovens', 'Freestanding Microwave Ovens', 20),
  ('Large Appliances', 'Ovens', 'Built-In Ovens', 10),
  ('Large Appliances', 'Range Hoods', 'Angled Hoods', 10),
  ('Large Appliances', 'Range Hoods', 'Chimney Hoods', 20),
  ('Large Appliances', 'Range Hoods', 'Island Hoods', 30),
  ('Large Appliances', 'Range Hoods', 'Downdraft Hoods', 40),
  ('Large Appliances', 'Range Hoods', 'Built-In Hoods', 50),
  ('Large Appliances', 'Range Hoods', 'Telescopic Hoods', 60),
  ('Large Appliances', 'Range Hoods', 'Under-Cabinet Hoods', 70),
  ('Large Appliances', 'Range Hoods', 'Ceiling Hoods', 80),
  ('Large Appliances', 'Refrigerators', 'Beverage Coolers', 10),
  ('Large Appliances', 'Refrigerators', 'Mini Fridges', 20),
  ('Large Appliances', 'Refrigerators', 'Portable Refrigerators', 30),
  ('Large Appliances', 'Refrigerators', 'Meat-Aging Refrigerators', 40),
  ('Large Appliances', 'Refrigerators', 'Fridges with Freezers', 50),
  ('Large Appliances', 'Refrigerators', 'Fridges without Freezers', 60),
  ('Large Appliances', 'Wine Coolers', 'Freestanding Wine Coolers', 10),
  ('Large Appliances', 'Wine Coolers', 'Built-In Wine Coolers', 20),
  ('Large Appliances', 'Wine Coolers', 'Under-Counter Wine Coolers', 30),
  ('Small Appliances', 'Air Fryers', 'Hot Air Fryers', 10),
  ('Small Appliances', 'Air Fryers', 'Air Fry Ovens', 20),
  ('Small Appliances', 'Beer Brewing & Dispensing', 'Home Breweries', 10),
  ('Small Appliances', 'Beer Brewing & Dispensing', 'Beer Dispensers', 20),
  ('Small Appliances', 'Coffee Makers', 'Espresso Coffee Makers', 10),
  ('Small Appliances', 'Coffee Makers', 'Filter Coffee Makers', 20),
  ('Small Appliances', 'Coffee Makers', 'Automatic Coffee Machines', 30),
  ('Small Appliances', 'Electric Grills', 'Raclette Grills', 10),
  ('Small Appliances', 'Electric Grills', 'Commercial Grills', 20),
  ('Small Appliances', 'Electric Grills', 'Steak Grills', 30),
  ('Small Appliances', 'Electric Grills', 'Kebab Grills', 40),
  ('Small Appliances', 'Food Dehydrators', 'Commercial Food Dehydrators', 10),
  ('Small Appliances', 'Food Dehydrators', 'Domestic Food Dehydrators', 20),
  ('Small Appliances', 'Hot Dog Makers', 'Hot Dog Makers', 10),
  ('Small Appliances', 'Ice Cream Makers', 'Ice Cream Makers', 10),
  ('Small Appliances', 'Ice Makers', 'Domestic Ice Makers', 10),
  ('Small Appliances', 'Ice Makers', 'Commercial Ice Makers', 20),
  ('Small Appliances', 'Ice Makers', 'Ice Crushers', 30),
  ('Small Appliances', 'Kettles', 'Kettles', 10),
  ('Small Appliances', 'Kitchen Machines', 'Stand Mixers', 10),
  ('Small Appliances', 'Kitchen Machines', 'Food Processors', 20),
  ('Small Appliances', 'Kitchen Machines', 'Juicers', 30),
  ('Small Appliances', 'Kitchen Machines', 'Mixers', 40),
  ('Small Appliances', 'Meat Grinders', 'Meat Grinders', 10),
  ('Small Appliances', 'Milk Makers', 'Milk Makers', 10),
  ('Small Appliances', 'Mini Ovens', 'Mini Ovens', 10),
  ('Small Appliances', 'Pasta Makers', 'Pasta Makers', 10),
  ('Small Appliances', 'Pizza Ovens', 'Pizza Ovens', 10),
  ('Small Appliances', 'Popcorn Makers', 'Popcorn Makers', 10),
  ('Small Appliances', 'Preserving Pots', 'Preserving Pots', 10),
  ('Small Appliances', 'Sous Vide', 'Sous Vide', 10),
  ('Small Appliances', 'Toasters', 'Toasters', 10),
  ('Small Appliances', 'Vacuum Cleaners', 'Stick Vacuum Cleaners', 10),
  ('Small Appliances', 'Vacuum Cleaners', 'Industrial Vacuum Cleaners', 20),
  ('Small Appliances', 'Water Filters', 'Undersink Filters', 10),
  ('Small Appliances', 'Water Filters', 'Countertop Filters', 20),
  ('Climate', 'Air Purifiers', 'Air Purifiers', 10),
  ('Climate', 'Cooling', 'Mobile Air Conditioners', 10),
  ('Climate', 'Cooling', 'Ceiling Fans', 20),
  ('Climate', 'Cooling', 'Air Coolers', 30),
  ('Climate', 'Cooling', 'Tower Fans', 40),
  ('Climate', 'Dehumidifiers', 'Home Dehumidifiers', 10),
  ('Climate', 'Dehumidifiers', 'Industrial Dehumidifiers', 20),
  ('Climate', 'Indoor Heaters', 'Infrared Panels', 10),
  ('Climate', 'Indoor Heaters', 'Designer Radiators', 20),
  ('Climate', 'Indoor Heaters', 'Electric Fireplaces', 30),
  ('Climate', 'Indoor Heaters', 'Convectors', 40),
  ('Climate', 'Indoor Heaters', 'Bathroom Radiators', 50),
  ('Climate', 'Indoor Heaters', 'Heating Blankets', 60),
  ('Climate', 'Indoor Heaters', 'Electric Radiators', 70),
  ('Climate', 'Outdoor Heaters', 'Infrared Heaters', 10),
  ('Climate', 'Outdoor Heaters', 'Ethanol Heaters', 20),
  ('Climate', 'Outdoor Heaters', 'Gas Heaters', 30),
  ('Climate', 'Water Heaters', 'Water Heaters', 10),
  ('Home & Décor', 'Bathroom', 'Toilet Seats', 10),
  ('Home & Décor', 'Bathroom', 'Bathroom Accessories', 20),
  ('Home & Décor', 'Dining & Tableware', 'Kids’ Water Bottles', 10),
  ('Home & Décor', 'Kitchen', 'Lunch Boxes', 10),
  ('Home & Décor', 'Kitchen', 'Kitchen Knives', 20),
  ('Home & Décor', 'Kitchen', 'Kitchen Sinks', 30),
  ('Home & Décor', 'Kitchen', 'Kitchen Helpers', 40),
  ('Home & Décor', 'Living & Home Accessories', 'Watch Winders', 10),
  ('Home & Décor', 'Waste & Storage', 'Bins For Sorted Waste', 10),
  ('Home & Décor', 'Waste & Storage', 'Touchless Waste Bins', 20),
  ('Home & Décor', 'Waste & Storage', 'Container Stands', 30),
  ('Sports & Leisure', 'Fitness Machines', 'Treadmills', 10),
  ('Sports & Leisure', 'Fitness Machines', 'Rowing Machines', 20),
  ('Sports & Leisure', 'Fitness Machines', 'Cardio Bikes', 30),
  ('Sports & Leisure', 'Fitness Machines', 'Vibration Platforms', 40),
  ('Sports & Leisure', 'Games & Entertainment', 'Dartboards', 10),
  ('Sports & Leisure', 'Kids Sports & Play', 'Kids Essentials', 10),
  ('Garden', 'Garden Furniture', 'Swings', 10),
  ('Garden', 'Garden Furniture', 'Sunbeds', 20),
  ('Garden', 'Garden Furniture', 'Loungers', 30),
  ('Garden', 'Garden Furniture', 'Garden Tables', 40),
  ('Garden', 'Garden Furniture', 'Garden Chairs', 50),
  ('Garden', 'Garden Structures & Shade', 'Gazebos', 10),
  ('Garden', 'Garden Structures & Shade', 'Pergolas', 20),
  ('Garden', 'Garden Structures & Shade', 'Privacy Screens', 30),
  ('Garden', 'Garden Structures & Shade', 'Umbrellas', 40),
  ('Garden', 'Garden Utilities', 'Firepits', 10),
  ('Garden', 'Garden Utilities', 'Fountains', 20),
  ('Garden', 'Garden Utilities', 'Garden Showers', 30),
  ('Garden', 'Garden Utilities', 'Firewood Stands', 40),
  ('Garden', 'Gardening & Equipment', 'Raised Garden Beds', 10),
  ('Garden', 'Gardening & Equipment', 'Wheelbarrows & Carts', 20),
  ('Garden', 'Grills', 'Electric Grills', 10),
  ('Garden', 'Grills', 'Charcoal Grills', 20),
  ('Garden', 'Grills', 'Kamado Grills', 30),
  ('Garden', 'Grills', 'Outdoor Pizza Ovens', 40),
  ('Garden', 'Grills', 'Smokers', 50),
  ('Garden', 'Outdoor Cooking & Kitchens', 'Outdoor Cooking & Kitchens', 10),
  ('Audio', 'Hifi Systems & Components', 'Turntables', 10),
  ('Audio', 'Hifi Systems & Components', 'Hifi Amplifiers', 20),
  ('Audio', 'Hifi Systems & Components', 'Hifi Cd Players', 30),
  ('Audio', 'Home Theaters', '5.1 Speaker Systems', 10);

-- Rows with no place in the tree. Declared up front so the filing step below skips them:
-- the empty duplicate "Chimney Hoods" shares a name with a real leaf and would otherwise
-- be filed alongside it.
CREATE TEMP TABLE _retired_l3 (id uuid, note text) ON COMMIT DROP;
INSERT INTO _retired_l3 (id, note) VALUES
  ('c6d8d538-b51d-4309-9fae-4f6bea2e5584', 'Hobs - Test'),
  ('a93170ed-84f3-4224-a8e4-9c64af86cf70', 'Hoods - Test'),
  ('8d0d1798-782a-4501-bcbd-6fd1c0b3029a', 'Chimney Hoods (empty duplicate)');

-- 7a. File existing leaves under their L2 (id, attributes and FKs preserved).
--     Only ever fills a NULL parent, so a hand-placed row is never overwritten.
UPDATE public.categories_l3 c
SET l2_id = l2.id, sort_order = t.sort_order
FROM _tree_l3 t
JOIN public.categories_l1 l1 ON l1.name = t.l1_name
JOIN public.categories_l2 l2 ON l2.l1_id = l1.id AND l2.name = t.l2_name
WHERE c.name = t.l3_name
  AND c.l2_id IS NULL
  AND c.id NOT IN (SELECT id FROM _retired_l3);

-- 7b. Insert the leaves that do not exist yet. A retired row does not count as an
--     existing leaf, so the real "Chimney Hoods" is still seeded if only the dup remains.
INSERT INTO public.categories_l3 (name, l2_id, sort_order, active, is_finalized)
SELECT t.l3_name, l2.id, t.sort_order, true, false
FROM _tree_l3 t
JOIN public.categories_l1 l1 ON l1.name = t.l1_name
JOIN public.categories_l2 l2 ON l2.l1_id = l1.id AND l2.name = t.l2_name
WHERE NOT EXISTS (
  SELECT 1 FROM public.categories_l3 c
  WHERE c.name = t.l3_name AND c.id NOT IN (SELECT id FROM _retired_l3)
);

-- 8. Retire the rows with no place in the tree ------------------------------
-- Kept, not deleted: deactivated and unparented so they show as Uncategorised and stay
-- out of the pickers. Reversible with a single UPDATE.

UPDATE public.categories_l3 c
SET active = false, l2_id = NULL
FROM _retired_l3 r
WHERE c.id = r.id;

NOTIFY pgrst, 'reload schema';

COMMIT;
