-- 167: Roadmap Creator — the reference/annotation split, and the guarantee that protects it.
--
-- WHAT THIS MODULE IS. Pivot the product catalogue into a per-category roadmap grid, mark what
-- is being replaced or retired, plan the gaps with placeholder cards, and present it — with the
-- economics hidden — to a supplier in the room. Ported from ProductToolkit's `apps/roadmap`
-- (SQL Server + Express); see docs/originflow-roadmap-creator-module.md for every decision, and
-- docs/originflow-port-three-modules.md §1 (lines 140-386) for the full feature/UI spec.
--
-- THE MODEL — TWO HALVES THAT MUST NEVER DAMAGE EACH OTHER.
--
--   REFERENCE (written only by an import)     ANNOTATIONS (written only by a person)
--     roadmap_import   one row per upload       roadmap_item_flag   per-SKU mark + comment
--     roadmap_sku      one row per SKU          roadmap_placer      one placeholder in one cell
--                                               roadmap_axis_value  hand-added family/row/column
--                                               roadmap_audit       append-only
--
-- THE LOAD-BEARING GUARANTEE. A refreshed export can insert and update reference rows but can
-- NEVER delete one, and never touches an annotation table at all. A SKU that drops out of a
-- newer export is marked is_current = false ("not in latest file") and still renders, dimmed,
-- so the EOL note somebody wrote against it is not silently lost. If it reappears in a later
-- file it flips back to true with its flag and comment still attached.
--
-- THREE THINGS HOLD THAT UP, AND ALL THREE ARE DELIBERATE:
--
--  1. `roadmap_import_skus()` below is an INSERT .. ON CONFLICT DO UPDATE. It has no delete
--     branch and cannot be given one by accident — this is strictly stronger than the source's
--     T-SQL MERGE, which relied on a missing `WHEN NOT MATCHED BY SOURCE` clause.
--  2. THERE ARE NO FOREIGN KEYS IN THIS SCHEMA. Not an omission. `roadmap_item_flag.sku` does
--     not reference `roadmap_sku.sku`, and `roadmap_sku.last_import_id` does not reference
--     `roadmap_import`. A flag MUST be able to outlive the SKU vanishing from an export —
--     adding the "obvious missing" FK would delete exactly the annotations this module exists
--     to protect. Referential integrity here is a bug, not a feature.
--  3. The import raises on an empty payload. Without that guard a failed browser-side parse
--     posts zero rows and the delist pass marks the entire catalogue not-current.
--
-- WHY THE IMPORT IS A FUNCTION AND NOT CLIENT WRITES. src/data/ports/database.port.ts has no
-- transaction primitive, and the upsert and the delist pass must be atomic or a mid-flight
-- failure delists everything. So the whole import is one SECURITY DEFINER function invoked
-- through db.rpc() — the escape hatch src/data/PORTING.md already documents for this case.
-- That also let the source's `roadmap_sku_stage` table disappear: jsonb_to_recordset replaces
-- it, which removes a TRUNCATE (needs table-owner rights on Supabase) and the bulk-load driver.
-- Six tables here, seven in the source.
--
-- WHAT WAS DROPPED FROM THE SOURCE SCHEMA. `roadmap_item_flag.approved` and
-- `roadmap_placer.approved` (BIT) — both superseded by `status` and documented as unused in
-- schema.sql:158-163. The source kept them because that file is additive-only on deployed
-- instances; this is a first creation, so they simply do not exist.
--
-- WHAT WAS ADDED. CHECK constraints on the enum-ish columns. The source validated these only
-- in routes.js, which meant a direct SQL write could store 'REPLACE' or 'Pending' and the board
-- would silently fail to match it. The value sets are closed and live in
-- src/pages/roadmap/roadmap.constants.ts — keep the two in step.

-- ── Reference data ───────────────────────────────────────────────────────────

create table if not exists public.roadmap_import (
  import_id      int generated by default as identity primary key,
  file_name      text,
  row_count      int not null default 0,
  inserted_count int not null default 0,
  updated_count  int not null default 0,
  delisted_count int not null default 0,
  imported_at    timestamptz not null default now(),
  imported_by    text
);
create index if not exists idx_roadmap_import_at on public.roadmap_import (imported_at desc);

create table if not exists public.roadmap_sku (
  sku             text primary key,
  description     text,
  family          text,
  -- The "category" a board is built for. Deliberately the export's own System Index string and
  -- NOT a categories_l3 FK: the workbook is the only place this value exists, and forcing a
  -- join would make an import fail on a category OriginFlow has never heard of.
  system_index    text,
  image_url       text,
  factory_price   numeric(18,4),
  supplier        text,
  shop_link       text,
  amazon_link     text,
  -- The 7 axis attributes (Main Color, Segment 01-05, IoT) as one object rather than 7 columns.
  -- They are never queried on their own — every pivot happens client-side in grid.ts — so an
  -- 8th axis is a constants edit with no DDL.
  attrs_json      jsonb not null default '{}'::jsonb,
  -- 2025 commercial
  nov_2025        numeric(18,2),
  nov_fc_2025     numeric(18,2),
  fc_ff_2025      numeric(18,6),
  noq_2025        numeric(18,2),
  sm_pct_2025     numeric(18,6),
  asp_2025        numeric(18,4),
  claim_rate_2025 numeric(18,6),
  -- 2026 commercial
  nov_2026        numeric(18,2),
  nov_fc_2026     numeric(18,2),
  fc_ff_2026      numeric(18,6),
  noq_2026        numeric(18,2),
  sm_pct_2026     numeric(18,6),
  asp_2026        numeric(18,4),
  claim_rate_2026 numeric(18,6),
  -- lifecycle
  is_current      boolean not null default true,
  first_seen_at   timestamptz not null default now(),
  last_seen_at    timestamptz not null default now(),
  last_import_id  int,          -- no FK, on purpose (see header, point 2)
  updated_by      text
);
create index if not exists idx_roadmap_sku_sysindex on public.roadmap_sku (system_index);

-- ── Annotations — never written by an import ─────────────────────────────────

create table if not exists public.roadmap_item_flag (
  sku          text primary key,   -- no FK, on purpose (see header, point 2)
  -- null means "a comment with no mark", which is a real state the board renders.
  flag         text check (flag is null or flag in ('replace','eol','aeol','upcoming')),
  comment      text,
  updated_at   timestamptz not null default now(),
  updated_by   text,
  -- The Summary tab's review of a Replacement / EOL row. `approved_by` is a NAME SNAPSHOT
  -- validated against roadmap_approvers() when it changes, never a uuid — see that function.
  status       text not null default 'pending'
                 check (status in ('pending','approved','rejected')),
  approved_by  text,
  project_code text
);

-- One placeholder card in one grid cell. The prototype keyed these by a single joined string
-- (category|yField|xField|family|yValue|xValue); the six parts are real columns here, which is
-- what turns "which annotations no longer match any SKU?" (the History tab's orphan report)
-- into a plain query rather than string surgery.
create table if not exists public.roadmap_placer (
  placer_id         int generated by default as identity primary key,
  category          text not null,
  y_field           text not null,
  x_field           text not null,
  family            text not null,
  y_value           text not null,
  x_value           text not null,
  type              text not null check (type in ('new','upcoming')),
  comment           text,
  sort_order        int not null default 0,
  created_at        timestamptz not null default now(),
  created_by        text,
  updated_at        timestamptz not null default now(),
  updated_by        text,
  -- project_code / status / approved_by / expected_2027_nic are only meaningful for
  -- type = 'new' rows (the Summary tab's New Projects table); left at their defaults for
  -- type = 'upcoming', which Summary does not show.
  project_code      text,
  status            text not null default 'pending'
                      check (status in ('pending','approved','rejected')),
  approved_by       text,
  -- A planner's manual revenue estimate for a SKU that does not exist yet, summed into a total
  -- once the row is Approved. Same precision as the imported nov_* columns.
  expected_2027_nic numeric(18,2)
);
create index if not exists idx_roadmap_placer_cat on public.roadmap_placer (category);

-- The prototype's addedFamilies / addedRows / addedCols, unified. `field` is the axis field a
-- row or column belongs to (an added "Copper" row only makes sense while Main Color is the Y
-- axis) and is null for a family.
create table if not exists public.roadmap_axis_value (
  axis_value_id int generated by default as identity primary key,
  kind          text not null check (kind in ('family','row','col')),
  category      text not null,
  field         text,
  value         text not null,
  created_at    timestamptz not null default now(),
  created_by    text
);

-- Two PARTIAL unique indexes rather than one four-column index. Postgres treats NULLs as
-- DISTINCT in a unique index, so `unique (category, kind, field, value)` alone would happily
-- store the same family twice (two rows with field = null). Splitting on the null-ness of
-- `field` is what actually makes both cases unique. (The source needed the same split for the
-- opposite reason — SQL Server treats NULLs as equal, so one index allowed only ONE family per
-- category. Same two indexes, different bug avoided.)
create unique index if not exists ux_roadmap_axis_value_nofield
  on public.roadmap_axis_value (category, kind, value) where field is null;
create unique index if not exists ux_roadmap_axis_value_field
  on public.roadmap_axis_value (category, kind, field, value) where field is not null;

-- Append-only. Re-flagging a SKU — even to the same value, changing only the comment — writes
-- a new row, so a note's edit history is on record too. Nothing ever updates this table.
create table if not exists public.roadmap_audit (
  audit_id    bigint generated by default as identity primary key,
  entity      text not null check (entity in ('flag','placer','axis','import')),
  entity_key  text,
  action      text not null check (action in ('set','clear','add','remove','edit','import')),
  category    text,
  sku         text,
  before_json jsonb,
  after_json  jsonb,
  changed_at  timestamptz not null default now(),
  changed_by  text
);
create index if not exists idx_roadmap_audit_cat on public.roadmap_audit (category, changed_at desc);
create index if not exists idx_roadmap_audit_at  on public.roadmap_audit (changed_at desc);

-- ── Who may write ────────────────────────────────────────────────────────────
--
-- The source guarded writes with a single positional middleware —
-- `router.use(requirePermission("roadmap","editor"))` at routes.js:134, with every write route
-- below it. That works right up until someone adds a route in the wrong place. RLS makes the
-- barrier structural instead: a policy cannot be left off the bottom of a file.
--
-- WHY THIS READS TWO TABLES. The roadmap's audience is PMs and category managers, but the two
-- role stores in this database disagree about who they are: `user_roles` holds 'admin' and
-- 'internal' (6 rows, what is_design_editor() reads), while `profiles.role` holds 'ADMIN' and
-- 'pm' (what ~30 other policies key off). Reading only user_roles would mean no PM could mark
-- a SKU, which is the entire job. Reading profiles too needs no backfill and matches the
-- majority convention. Revisit if the two stores are ever reconciled.
create or replace function public.is_roadmap_editor()
  returns boolean
  language sql
  stable security definer
  set search_path to ''
as $$
  select exists (
    select 1 from public.user_roles r
    where r.user_id = auth.uid() and r.role in ('admin', 'internal')
  ) or exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and upper(p.role) in ('ADMIN', 'PM')
  );
$$;

-- ── Who may approve ──────────────────────────────────────────────────────────
--
-- Editing the roadmap and APPROVING a New Project / Replacement / EOL row are different rights.
-- Every PM marks SKUs; the Summary tab's decision belongs to the admins.
--
-- The source hardcoded `MANAGERS = ["Fabio", "Nicolas"]` in two files (config/constants.js and
-- mapping.js) because ProductToolkit had no approver concept to reuse. Those two people were
-- right, and they are admins here — but so are the other two, and a hardcoded list silently
-- stops being true the moment somebody joins or leaves. The list is derived instead.
--
-- WHY profiles.role AND NOT is_super_admin. Verified live 2026-09-09: `is_super_admin` is one
-- person, which is not the approver group. `profiles.role = 'ADMIN'` and `user_roles.role =
-- 'admin'` both resolve to the same four people, and profiles.role is the convention ~30 other
-- policies already key off, so it is the one used here.
--
-- WHY approved_by STAYS A NAME AND NOT A UUID. It is a snapshot of who decided, not a live link.
-- An approval must still read correctly after that person is renamed, loses admin, or leaves —
-- the same reasoning that keeps foreign keys out of this schema, applied to people instead of
-- SKUs. The trigger below therefore validates only when the value CHANGES.

create or replace function public.roadmap_approvers()
  returns table (user_id uuid, name text)
  language sql
  stable security definer
  set search_path to ''
as $$
  select p.id, p.name
  from public.profiles p
  where auth.uid() is not null
    and upper(p.role) = 'ADMIN'
    and nullif(btrim(coalesce(p.name, '')), '') is not null
  order by p.name;
$$;

-- The source validated `approvedBy ∈ MANAGERS` in routes.js. Writes here go straight to
-- PostgREST, so there is no route layer left to check it in — without this trigger any editor
-- could record an approval by anyone, or by a typo. Same reasoning as putting the write barrier
-- in RLS rather than in middleware: the check belongs where it cannot be bypassed.
create or replace function public.roadmap_validate_approver()
  returns trigger
  language plpgsql
  security definer
  set search_path to ''
as $$
begin
  if new.approved_by is not null
     and (tg_op = 'INSERT' or new.approved_by is distinct from old.approved_by)
     and not exists (
       select 1 from public.profiles p
       where upper(p.role) = 'ADMIN'
         and btrim(lower(p.name)) = btrim(lower(new.approved_by))
     )
  then
    -- Plain hyphen, no apostrophe: this string is re-typed by hand into SQL consoles often
    -- enough that dollar-quoting plus an escaped apostrophe is a trap worth not setting.
    raise exception '% is not an approver - the Summary tab decision is an admin right',
      new.approved_by
      using errcode = '23514';
  end if;
  return new;
end;
$$;

drop trigger if exists trg_roadmap_flag_approver on public.roadmap_item_flag;
create trigger trg_roadmap_flag_approver
  before insert or update on public.roadmap_item_flag
  for each row execute function public.roadmap_validate_approver();

drop trigger if exists trg_roadmap_placer_approver on public.roadmap_placer;
create trigger trg_roadmap_placer_approver
  before insert or update on public.roadmap_placer
  for each row execute function public.roadmap_validate_approver();

-- ── The import ───────────────────────────────────────────────────────────────
--
-- One call, one transaction. `p_rows` is the parsed workbook already reduced to the ~30 fields
-- that are kept — roughly 2MB for a 2,500-row export — with column names matching this table
-- exactly, produced by toImportRows() in src/services/roadmap/roadmap-mapping.ts. The trimming,
-- truncation and number coercion all happen there, where they are unit-tested; this function
-- deliberately does no cleaning, so there is exactly one place that decides what a value means.
create or replace function public.roadmap_import_skus(p_rows jsonb, p_file_name text)
  returns table (
    import_id      int,
    row_count      int,
    inserted_count int,
    updated_count  int,
    delisted_count int
  )
  language plpgsql
  security definer
  set search_path to ''
as $$
declare
  v_import_id int;
  v_actor     text;
  v_rows      int;
  v_inserted  int;
  v_updated   int;
  v_delisted  int;
begin
  -- SECURITY DEFINER bypasses RLS, so the gate has to be re-asserted here by hand. Without
  -- this line any authenticated user could rewrite the whole reference catalogue.
  if not public.is_roadmap_editor() then
    raise exception 'Not authorised to import roadmap data'
      using errcode = '42501';
  end if;

  -- DEFENCE #3 (see header). An empty payload means the browser-side parse produced nothing —
  -- a wrong file, a renamed sheet, a thrown error. Committing it would run the delist pass
  -- against zero SKUs and mark the entire catalogue "not in latest file".
  if p_rows is null or jsonb_typeof(p_rows) <> 'array' or jsonb_array_length(p_rows) = 0 then
    raise exception 'Refusing to import an empty row set'
      using errcode = '22023';
  end if;

  v_rows := jsonb_array_length(p_rows);

  select coalesce(p.name, p.email, auth.uid()::text) into v_actor
  from public.profiles p where p.id = auth.uid();

  insert into public.roadmap_import (file_name, row_count, imported_by)
  values (nullif(btrim(coalesce(p_file_name, '')), ''), v_rows, v_actor)
  returning public.roadmap_import.import_id into v_import_id;

  with src as (
    -- The authoritative last-one-wins dedupe is in toImportRows(); this is the net that stops
    -- a hand-edited file from raising "ON CONFLICT cannot affect row a second time", which is
    -- an error the planner can do nothing with. Either surviving row is acceptable here.
    select distinct on (r.sku) r.*
    from jsonb_to_recordset(p_rows) as r(
      sku             text,
      description     text,
      family          text,
      system_index    text,
      image_url       text,
      factory_price   numeric,
      supplier        text,
      shop_link       text,
      amazon_link     text,
      attrs_json      jsonb,
      nov_2025        numeric,
      nov_fc_2025     numeric,
      fc_ff_2025      numeric,
      noq_2025        numeric,
      sm_pct_2025     numeric,
      asp_2025        numeric,
      claim_rate_2025 numeric,
      nov_2026        numeric,
      nov_fc_2026     numeric,
      fc_ff_2026      numeric,
      noq_2026        numeric,
      sm_pct_2026     numeric,
      asp_2026        numeric,
      claim_rate_2026 numeric
    )
    where nullif(btrim(coalesce(r.sku, '')), '') is not null
    order by r.sku
  ),
  merged as (
    insert into public.roadmap_sku (
      sku, description, family, system_index, image_url, factory_price, supplier,
      shop_link, amazon_link, attrs_json,
      nov_2025, nov_fc_2025, fc_ff_2025, noq_2025, sm_pct_2025, asp_2025, claim_rate_2025,
      nov_2026, nov_fc_2026, fc_ff_2026, noq_2026, sm_pct_2026, asp_2026, claim_rate_2026,
      is_current, last_seen_at, last_import_id, updated_by
    )
    select
      s.sku, s.description, s.family, s.system_index, s.image_url, s.factory_price, s.supplier,
      s.shop_link, s.amazon_link, coalesce(s.attrs_json, '{}'::jsonb),
      s.nov_2025, s.nov_fc_2025, s.fc_ff_2025, s.noq_2025, s.sm_pct_2025, s.asp_2025, s.claim_rate_2025,
      s.nov_2026, s.nov_fc_2026, s.fc_ff_2026, s.noq_2026, s.sm_pct_2026, s.asp_2026, s.claim_rate_2026,
      true, now(), v_import_id, v_actor
    from src s
    on conflict (sku) do update set
      description     = excluded.description,
      family          = excluded.family,
      system_index    = excluded.system_index,
      image_url       = excluded.image_url,
      factory_price   = excluded.factory_price,
      supplier        = excluded.supplier,
      shop_link       = excluded.shop_link,
      amazon_link     = excluded.amazon_link,
      attrs_json      = excluded.attrs_json,
      nov_2025        = excluded.nov_2025,
      nov_fc_2025     = excluded.nov_fc_2025,
      fc_ff_2025      = excluded.fc_ff_2025,
      noq_2025        = excluded.noq_2025,
      sm_pct_2025     = excluded.sm_pct_2025,
      asp_2025        = excluded.asp_2025,
      claim_rate_2025 = excluded.claim_rate_2025,
      nov_2026        = excluded.nov_2026,
      nov_fc_2026     = excluded.nov_fc_2026,
      fc_ff_2026      = excluded.fc_ff_2026,
      noq_2026        = excluded.noq_2026,
      sm_pct_2026     = excluded.sm_pct_2026,
      asp_2026        = excluded.asp_2026,
      claim_rate_2026 = excluded.claim_rate_2026,
      -- A SKU that dropped out and came back is current again, with its flag untouched.
      is_current      = true,
      last_seen_at    = now(),
      last_import_id  = v_import_id,
      updated_by      = v_actor
      -- first_seen_at is deliberately NOT in this list: it records when the SKU was first
      -- ever seen, not when it was last refreshed.
    -- DEFENCE #1 (see header): there is no delete branch, and ON CONFLICT cannot have one.
    returning (xmax = 0) as was_insert
  )
  -- Postgres has no $action. A freshly inserted row carries xmax = 0; an updated one does not.
  select
    count(*) filter (where merged.was_insert),
    count(*) filter (where not merged.was_insert)
  into v_inserted, v_updated
  from merged;

  -- Everything the import did not touch drops out of "latest file" but keeps its row, its
  -- annotations and its history. This is the only statement that reacts to absence, and it
  -- only ever flips a flag — it never deletes.
  update public.roadmap_sku
     set is_current = false
   where is_current
     and (last_import_id is null or last_import_id <> v_import_id);
  get diagnostics v_delisted = row_count;

  update public.roadmap_import i
     set inserted_count = v_inserted,
         updated_count  = v_updated,
         delisted_count = v_delisted
   where i.import_id = v_import_id;

  insert into public.roadmap_audit (entity, entity_key, action, changed_by, after_json)
  values (
    'import', v_import_id::text, 'import', v_actor,
    jsonb_build_object(
      'fileName', nullif(btrim(coalesce(p_file_name, '')), ''),
      'rowCount', v_rows,
      'inserted', v_inserted,
      'updated',  v_updated,
      'delisted', v_delisted
    )
  );

  return query
    select v_import_id, v_rows, v_inserted, v_updated, v_delisted;
end;
$$;

-- The board's category picker: every System Index with its SKU counts. A plain aggregate, but
-- database.port.ts has no GROUP BY, so it lives here rather than pulling 2,500 rows to the
-- browser to count them.
create or replace function public.roadmap_categories()
  returns table (system_index text, sku_count bigint, current_count bigint)
  language sql
  stable security definer
  set search_path to ''
as $$
  select s.system_index,
         count(*) as sku_count,
         count(*) filter (where s.is_current) as current_count
  from public.roadmap_sku s
  where auth.uid() is not null
    and nullif(btrim(coalesce(s.system_index, '')), '') is not null
  group by s.system_index
  order by s.system_index;
$$;

-- ── RLS ──────────────────────────────────────────────────────────────────────
--
-- Read for any signed-in user: a roadmap is a planning artefact for the whole company and
-- nothing here is project-scoped, so can_see_project() does not apply.
--
-- Write for roadmap editors — EXCEPT the two reference tables, which get no write policy at
-- all. Their only writer is roadmap_import_skus() above, which is SECURITY DEFINER and so
-- bypasses RLS. That turns "reference data is written only by an import" from a convention
-- into a fact of the database: there is no policy that would let a person UPDATE roadmap_sku
-- through PostgREST, however they are logged in.
--
-- There is no anon policy anywhere here. This module has no portal and no token.

alter table public.roadmap_import     enable row level security;
alter table public.roadmap_sku        enable row level security;
alter table public.roadmap_item_flag  enable row level security;
alter table public.roadmap_placer     enable row level security;
alter table public.roadmap_axis_value enable row level security;
alter table public.roadmap_audit      enable row level security;

drop policy if exists "roadmap_import_read" on public.roadmap_import;
create policy "roadmap_import_read" on public.roadmap_import
  for select to authenticated using (true);

drop policy if exists "roadmap_sku_read" on public.roadmap_sku;
create policy "roadmap_sku_read" on public.roadmap_sku
  for select to authenticated using (true);

drop policy if exists "roadmap_item_flag_read" on public.roadmap_item_flag;
create policy "roadmap_item_flag_read" on public.roadmap_item_flag
  for select to authenticated using (true);

drop policy if exists "roadmap_item_flag_write" on public.roadmap_item_flag;
create policy "roadmap_item_flag_write" on public.roadmap_item_flag
  for all to authenticated
  using (public.is_roadmap_editor())
  with check (public.is_roadmap_editor());

drop policy if exists "roadmap_placer_read" on public.roadmap_placer;
create policy "roadmap_placer_read" on public.roadmap_placer
  for select to authenticated using (true);

drop policy if exists "roadmap_placer_write" on public.roadmap_placer;
create policy "roadmap_placer_write" on public.roadmap_placer
  for all to authenticated
  using (public.is_roadmap_editor())
  with check (public.is_roadmap_editor());

drop policy if exists "roadmap_axis_value_read" on public.roadmap_axis_value;
create policy "roadmap_axis_value_read" on public.roadmap_axis_value
  for select to authenticated using (true);

drop policy if exists "roadmap_axis_value_write" on public.roadmap_axis_value;
create policy "roadmap_axis_value_write" on public.roadmap_axis_value
  for all to authenticated
  using (public.is_roadmap_editor())
  with check (public.is_roadmap_editor());

drop policy if exists "roadmap_audit_read" on public.roadmap_audit;
create policy "roadmap_audit_read" on public.roadmap_audit
  for select to authenticated using (true);

-- Append-only in the strong sense: INSERT is allowed, UPDATE and DELETE have no policy, so the
-- log cannot be rewritten by anyone who reaches it through PostgREST.
drop policy if exists "roadmap_audit_append" on public.roadmap_audit;
create policy "roadmap_audit_append" on public.roadmap_audit
  for insert to authenticated
  with check (public.is_roadmap_editor());

-- Blanket table grants with RLS as the boundary, matching every other table in this schema.
-- Note roadmap_sku/roadmap_import get no insert/update/delete grant either: belt and braces
-- with the missing write policies above.
-- REVOKE FIRST — this is not belt-and-braces, it is a correction. Supabase ships
-- `alter default privileges in schema public grant all on tables to anon, authenticated`, so
-- every table created above arrives with INSERT/UPDATE/DELETE/TRUNCATE already granted to BOTH
-- roles. Verified live 2026-09-09: anon held all seven privileges on all six roadmap tables.
--
-- RLS still denied all of it — every policy here is `to authenticated`, and anon has no policy at
-- all, so with RLS enabled anon can do nothing. But that means ONE permissive `for all to public`
-- policy added later would silently hand anon write access to the whole module. Revoking makes
-- the grant layer agree with the policy layer instead of relying on it.
--
-- service_role is left alone deliberately: it bypasses RLS by design, is never reachable from a
-- browser, and every other table in this schema leaves it as Supabase set it.
revoke all on public.roadmap_import     from anon, authenticated;
revoke all on public.roadmap_sku        from anon, authenticated;
revoke all on public.roadmap_item_flag  from anon, authenticated;
revoke all on public.roadmap_placer     from anon, authenticated;
revoke all on public.roadmap_axis_value from anon, authenticated;
revoke all on public.roadmap_audit      from anon, authenticated;

-- Now the grants this module actually wants. The two reference tables get SELECT only: their
-- only writer is roadmap_import_skus(), which is SECURITY DEFINER and bypasses both layers.
grant select                         on public.roadmap_import     to authenticated;
grant select                         on public.roadmap_sku        to authenticated;
grant select, insert, update, delete on public.roadmap_item_flag  to authenticated;
grant select, insert, update, delete on public.roadmap_placer     to authenticated;
grant select, insert, update, delete on public.roadmap_axis_value to authenticated;
-- Append-only at the grant layer too: no update, no delete.
grant select, insert                 on public.roadmap_audit      to authenticated;

grant usage, select on sequence public.roadmap_placer_placer_id_seq     to authenticated;
grant usage, select on sequence public.roadmap_axis_value_axis_value_id_seq to authenticated;
grant usage, select on sequence public.roadmap_audit_audit_id_seq       to authenticated;

grant execute on function public.is_roadmap_editor()                      to authenticated;
grant execute on function public.roadmap_import_skus(jsonb, text)         to authenticated;
grant execute on function public.roadmap_categories()                     to authenticated;
grant execute on function public.roadmap_approvers()                      to authenticated;
