/**
 * Supplier service
 * Manages supplier information and portal tokens
 */

import { auth, db, portalDb, orEmpty, orUndefined, withDeadline, type Row } from '../../data';
import { isLive } from '../../config/environment.config';
import { Supplier, User, Project } from '../../types';
import { mapSupplier, mapProfile, mapProject } from '../../utils/mappers.utils';
import { generateUUID, generateNumericCode, asPortalLockedError } from '../../utils';

/** Bound for dashboard reads so a stalled connection fails fast instead of hanging the spinner. */
const READ_TIMEOUT_MS = 20000;

/**
 * Get all suppliers
 */
export const getSuppliers = async (): Promise<Supplier[]> => {
    if (!isLive) return [];
    const rows = await orEmpty(
        withDeadline((signal) => db.select<Row>('suppliers', { signal }), READ_TIMEOUT_MS, 'getSuppliers'),
        'getSuppliers',
    );
    return rows.map(mapSupplier);
};

/**
 * Get supplier by ID
 */
export const getSupplierById = async (id: string): Promise<Supplier | undefined> => {
    if (!id || !isLive) return undefined;
    const row = await orUndefined(db.selectMaybeOne<Row>('suppliers', { where: { id } }), 'getSupplierById');
    return row ? mapSupplier(row) : undefined;
};

/**
 * Get supplier by portal token (public supplier portal).
 *
 * Uses the get_supplier_by_token_safe SECURITY DEFINER routine rather than a direct
 * table read: the suppliers table is not readable by the anonymous `anon` role
 * the portal client runs as, and the routine returns has_access_code instead of the
 * access code itself so the secret is never exposed to the browser.
 */
export const getSupplierByToken = async (token: string): Promise<Supplier | undefined> => {
    if (!isLive || !token) return undefined;
    const data = await orUndefined(
        portalDb.rpc<Row | Row[] | null>('get_supplier_by_token_safe', { p_token: token }),
        'getSupplierByToken',
    );
    const row = Array.isArray(data) ? data[0] : data;
    return row ? mapSupplier(row) : undefined;
};

/**
 * Verify a supplier's access code against the portal token (server-side).
 *
 * Uses the verify_supplier_access SECURITY DEFINER routine so the access code is
 * validated in the database and never sent to or compared in the browser.
 * Returns the supplier on success, or undefined when the code is incorrect.
 */
export const verifySupplierPortalAccess = async (token: string, code: string): Promise<Supplier | undefined> => {
    if (!isLive || !token || !code) return undefined;
    // Not wrapped in orUndefined: a brute-force lockout must propagate to the UI as a
    // clear "please wait" message. Any other failure still degrades to undefined
    // (treated as an incorrect code), preserving the previous resilient behaviour.
    try {
        const data = await portalDb.rpc<Row | Row[] | null>('verify_supplier_access', { p_token: token, p_code: code });
        const row = Array.isArray(data) ? data[0] : data;
        return row ? mapSupplier(row) : undefined;
    } catch (e) {
        const locked = asPortalLockedError(e);
        if (locked) throw locked;
        console.error('verifySupplierAccess failed:', e);
        return undefined;
    }
};

/**
 * Create a new supplier
 */
export const createSupplier = async (name: string, code: string, email: string): Promise<Supplier> => {
    const created = await db.insert<Row>('suppliers', { name, code, email });
    return mapSupplier(created);
};

/**
 * Update supplier information
 */
export const updateSupplier = async (id: string, updates: Partial<Supplier>): Promise<Supplier> => {
    const updated = await db.update<Row>('suppliers', {
        name: updates.name,
        code: updates.code,
        email: updates.email
    }, { where: { id } });
    return mapSupplier(updated);
};

/**
 * Generate a 6-digit numeric access code
 * Used only for manual regeneration (initial codes are auto-generated by database)
 */
const generateAccessCode = (): string => {
    return generateNumericCode(6);
};

/**
 * Regenerate supplier access code (for resending via email)
 * Note: Portal token and initial access code are auto-generated by database triggers
 */
export const regenerateSupplierAccessCode = async (supplierId: string): Promise<string> => {
    if (!supplierId) throw new Error("Supplier ID is required");

    const sup = await getSupplierById(supplierId);
    if (!sup) throw new Error("Supplier not found");

    const accessCode = generateAccessCode();
    if (!accessCode) {
        throw new Error("Failed to generate new access code");
    }

    const data = await db.update<Row>(
        'suppliers',
        { access_code: accessCode },
        { where: { id: supplierId }, columns: 'access_code' },
    );

    if (!data?.access_code) {
        throw new Error("New access code was not saved properly. Please try again.");
    }

    return data.access_code;
};

export const ensureSupplierToken = async (supplierId: string): Promise<string> => {
    if (!supplierId) throw new Error("Supplier ID is required");
    const sup = await getSupplierById(supplierId);
    if (!sup) throw new Error("Supplier not found");
    if (sup.portalToken) return sup.portalToken;
    const token = generateUUID();
    await db.updateWhere('suppliers', { portal_token: token }, { where: { id: supplierId } });
    return token;
};

export const assignSupplierToPMs = async (supplierId: string, pmIds: string[]): Promise<void> => {
    if (!supplierId || !pmIds.length) return;
    const user = await auth.getUser();
    await db.delete('supplier_pm_assignments', { where: { supplier_id: supplierId } });
    const assignments = pmIds.map(pmId => ({ supplier_id: supplierId, pm_id: pmId, assigned_by: user?.id }));
    await db.insertMany('supplier_pm_assignments', assignments);
};

export const getSupplierPMs = async (supplierId: string): Promise<User[]> => {
    if (!supplierId || !isLive) return [];
    const assignments = await orEmpty(
        db.select<Row>('supplier_pm_assignments', { columns: 'pm_id', where: { supplier_id: supplierId } }),
        'getSupplierPMs:assignments',
    );
    const pmIds = assignments.map((d: any) => d.pm_id);
    if (!pmIds.length) return [];
    const profiles = await orEmpty(
        db.select<Row>('profiles', { where: { id: pmIds } }),
        'getSupplierPMs:profiles',
    );
    return profiles.map(mapProfile);
};

export const reassignProjectPM = async (projectId: string, newPmId: string): Promise<Project> => {
    const data = await db.update<Row>('projects', { pm_id: newPmId }, { where: { id: projectId } });
    if (!data) throw new Error('reassignProjectPM: no data returned');
    return mapProject(data);
};

export const logAccessCodeAttempt = async (
    supplierId: string,
    accessCode: string,
    ipAddress: string,
    success: boolean
): Promise<void> => {
    try {
        await portalDb.insertMany('supplier_access_logs', [{
            supplier_id: supplierId,
            access_code: accessCode,
            ip_address: ipAddress,
            success,
            created_at: new Date().toISOString()
        }]);
    } catch (e) {
        console.error('Error logging access code attempt:', e);
    }
};
