/**
 * Supplier service
 * Manages supplier information and portal tokens
 */

import { supabase, portalClient } from '../core/supabase.client';
import { isLive } from '../../config/environment.config';
import { Supplier } from '../../types';
import { mapSupplier } from '../../utils/mappers.utils';
import { handleError } from '../../utils';

/**
 * Get all suppliers
 */
export const getSuppliers = async (): Promise<Supplier[]> => {
    if (!isLive) return [];
    const { data, error } = await supabase.from('suppliers').select('*');
    if (error) {
        console.error("getSuppliers failed", error);
        return [];
    }
    return (data || []).map(mapSupplier);
};

/**
 * Get supplier by ID
 */
export const getSupplierById = async (id: string): Promise<Supplier | undefined> => {
    if (!id || !isLive) return undefined;
    const { data, error } = await supabase.from('suppliers').select('*').eq('id', id).single();
    if (error || !data) return undefined;
    return mapSupplier(data);
};

/**
 * Get supplier by portal token
 */
export const getSupplierByToken = async (token: string): Promise<Supplier | undefined> => {
    if (!isLive) return undefined;
    const { data, error } = await portalClient.from('suppliers').select('*').eq('portal_token', token).maybeSingle();
    if (error) return undefined;
    return data ? mapSupplier(data) : undefined;
};

/**
 * Create a new supplier
 */
export const createSupplier = async (name: string, code: string, email: string): Promise<Supplier> => {
    const { data, error } = await supabase.from('suppliers').insert({ name, code, email }).select().single();
    if (error) handleError(error, 'createSupplier');
    return mapSupplier(data);
};

/**
 * Update supplier information
 */
export const updateSupplier = async (id: string, updates: Partial<Supplier>): Promise<Supplier> => {
    const { data, error } = await supabase.from('suppliers').update({
        name: updates.name,
        code: updates.code,
        email: updates.email
    }).eq('id', id).select().single();
    if (error) handleError(error, 'updateSupplier');
    return mapSupplier(data);
};

/**
 * Generate a 6-digit numeric access code
 * Used only for manual regeneration (initial codes are auto-generated by database)
 */
const generateAccessCode = (): string => {
    return Math.floor(Math.random() * 1000000).toString().padStart(6, '0');
};

/**
 * Regenerate supplier access code (for resending via email)
 * Note: Portal token and initial access code are auto-generated by database triggers
 */
export const regenerateSupplierAccessCode = async (supplierId: string): Promise<string> => {
    if (!supplierId) throw new Error("Supplier ID is required");

    const sup = await getSupplierById(supplierId);
    if (!sup) throw new Error("Supplier not found");

    const accessCode = generateAccessCode();
    if (!accessCode) {
        throw new Error("Failed to generate new access code");
    }

    const { data, error } = await supabase
        .from('suppliers')
        .update({ access_code: accessCode })
        .eq('id', supplierId)
        .select('access_code')
        .single();

    if (error) {
        console.error('Error regenerating access code:', error);
        handleError(error, 'regenerateSupplierAccessCode');
        throw new Error(`Failed to regenerate access code: ${error.message}`);
    }

    if (!data?.access_code) {
        throw new Error("New access code was not saved properly. Please try again.");
    }

    return data.access_code;
};
