/**
 * Supplier service
 * Manages supplier information and portal tokens
 */

import { supabase, portalClient } from '../core/supabase.client';
import { isLive } from '../../config/environment.config';
import { Supplier, User, Project } from '../../types';
import { mapSupplier, mapProfile, mapProject } from '../../utils/mappers.utils';
import { handleError, generateUUID, generateNumericCode } from '../../utils';
import { runMutation, runQuery } from '../core/db';
import { withTimeout } from '../core/with-timeout';

/** Bound for dashboard reads so a stalled connection fails fast instead of hanging the spinner. */
const READ_TIMEOUT_MS = 20000;

/**
 * Get all suppliers
 */
export const getSuppliers = async (): Promise<Supplier[]> => {
    if (!isLive) return [];
    try {
        const { data, error } = await withTimeout(supabase.from('suppliers').select('*'), READ_TIMEOUT_MS);
        if (error) {
            console.error("getSuppliers failed", error);
            return [];
        }
        return (data || []).map(mapSupplier);
    } catch (e) {
        console.error("[read] getSuppliers timed out or failed", e);
        return [];
    }
};

/**
 * Get supplier by ID
 */
export const getSupplierById = async (id: string): Promise<Supplier | undefined> => {
    if (!id || !isLive) return undefined;
    const { data, error } = await supabase.from('suppliers').select('*').eq('id', id).single();
    if (error || !data) return undefined;
    return mapSupplier(data);
};

/**
 * Get supplier by portal token (public supplier portal).
 *
 * Uses the get_supplier_by_token_safe SECURITY DEFINER RPC rather than a direct
 * table read: the suppliers table is not readable by the anonymous `anon` role
 * the portal client runs as, and the RPC returns has_access_code instead of the
 * access code itself so the secret is never exposed to the browser.
 */
export const getSupplierByToken = async (token: string): Promise<Supplier | undefined> => {
    if (!isLive || !token) return undefined;
    const { data, error } = await portalClient.rpc('get_supplier_by_token_safe', { p_token: token });
    if (error) {
        console.error('getSupplierByToken failed', error);
        return undefined;
    }
    const row = Array.isArray(data) ? data[0] : data;
    return row ? mapSupplier(row) : undefined;
};

/**
 * Verify a supplier's access code against the portal token (server-side).
 *
 * Uses the verify_supplier_access SECURITY DEFINER RPC so the access code is
 * validated in the database and never sent to or compared in the browser.
 * Returns the supplier on success, or undefined when the code is incorrect.
 */
export const verifySupplierPortalAccess = async (token: string, code: string): Promise<Supplier | undefined> => {
    if (!isLive || !token || !code) return undefined;
    const { data, error } = await portalClient.rpc('verify_supplier_access', { p_token: token, p_code: code });
    if (error) {
        console.error('verifySupplierAccess failed', error);
        return undefined;
    }
    const row = Array.isArray(data) ? data[0] : data;
    return row ? mapSupplier(row) : undefined;
};

/**
 * Create a new supplier
 */
export const createSupplier = async (name: string, code: string, email: string): Promise<Supplier> => {
    const data = await runQuery(supabase.from('suppliers').insert({ name, code, email }).select().single(), 'createSupplier');
    return mapSupplier(data);
};

/**
 * Update supplier information
 */
export const updateSupplier = async (id: string, updates: Partial<Supplier>): Promise<Supplier> => {
    const { data, error } = await supabase.from('suppliers').update({
        name: updates.name,
        code: updates.code,
        email: updates.email
    }).eq('id', id).select().single();
    if (error) handleError(error, 'updateSupplier');
    return mapSupplier(data);
};

/**
 * Generate a 6-digit numeric access code
 * Used only for manual regeneration (initial codes are auto-generated by database)
 */
const generateAccessCode = (): string => {
    return generateNumericCode(6);
};

/**
 * Regenerate supplier access code (for resending via email)
 * Note: Portal token and initial access code are auto-generated by database triggers
 */
export const regenerateSupplierAccessCode = async (supplierId: string): Promise<string> => {
    if (!supplierId) throw new Error("Supplier ID is required");

    const sup = await getSupplierById(supplierId);
    if (!sup) throw new Error("Supplier not found");

    const accessCode = generateAccessCode();
    if (!accessCode) {
        throw new Error("Failed to generate new access code");
    }

    const { data, error } = await supabase
        .from('suppliers')
        .update({ access_code: accessCode })
        .eq('id', supplierId)
        .select('access_code')
        .single();

    if (error) {
        console.error('Error regenerating access code:', error);
        handleError(error, 'regenerateSupplierAccessCode');
        throw new Error(`Failed to regenerate access code: ${error.message}`);
    }

    if (!data?.access_code) {
        throw new Error("New access code was not saved properly. Please try again.");
    }

    return data.access_code;
};

export const ensureSupplierToken = async (supplierId: string): Promise<string> => {
    if (!supplierId) throw new Error("Supplier ID is required");
    const sup = await getSupplierById(supplierId);
    if (!sup) throw new Error("Supplier not found");
    if (sup.portalToken) return sup.portalToken;
    const token = generateUUID();
    await runMutation(supabase.from('suppliers').update({ portal_token: token }).eq('id', supplierId), 'ensureSupplierToken');
    return token;
};

export const assignSupplierToPMs = async (supplierId: string, pmIds: string[]): Promise<void> => {
    if (!supplierId || !pmIds.length) return;
    const { data: { user } } = await supabase.auth.getUser();
    const { error: deleteError } = await supabase.from('supplier_pm_assignments').delete().eq('supplier_id', supplierId);
    if (deleteError) handleError(deleteError, 'assignSupplierToPMs');
    const assignments = pmIds.map(pmId => ({ supplier_id: supplierId, pm_id: pmId, assigned_by: user?.id }));
    await runMutation(supabase.from('supplier_pm_assignments').insert(assignments), 'assignSupplierToPMs');
};

export const getSupplierPMs = async (supplierId: string): Promise<User[]> => {
    if (!supplierId || !isLive) return [];
    const { data, error } = await supabase.from('supplier_pm_assignments').select('pm_id').eq('supplier_id', supplierId);
    if (error) return [];
    const pmIds = (data || []).map((d: any) => d.pm_id);
    if (!pmIds.length) return [];
    const { data: profiles, error: profileError } = await supabase.from('profiles').select('*').in('id', pmIds);
    if (profileError) return [];
    return (profiles || []).map(mapProfile);
};

export const reassignProjectPM = async (projectId: string, newPmId: string): Promise<Project> => {
    const { data, error } = await supabase.from('projects').update({ pm_id: newPmId }).eq('id', projectId).select().single();
    if (error) handleError(error, 'reassignProjectPM');
    if (!data) throw new Error('reassignProjectPM: no data returned');
    return mapProject(data);
};

export const logAccessCodeAttempt = async (
    supplierId: string,
    accessCode: string,
    ipAddress: string,
    success: boolean
): Promise<void> => {
    try {
        const { error } = await portalClient.from('supplier_access_logs').insert({
            supplier_id: supplierId,
            access_code: accessCode,
            ip_address: ipAddress,
            success,
            created_at: new Date().toISOString()
        });
        if (error) {
            console.error('Failed to log access code attempt:', error);
        }
    } catch (e) {
        console.error('Error logging access code attempt:', e);
    }
};
